### PR TITLE
Fix augenrules location

### PR DESCRIPTION
**Pull request by mj84**
augenrules is located at /sbin/augenrules, not /usr/sbin/augenrules

### CODE REVIEW

**Comment by uk-bolly** [comment]
hi @mj84 

Thank you for taking the time to raise this PR. Just wanted to double check this one. I am running this on a RockyLinux server and get the following output.

```
rocky9-bios ~# augenrules --check
/usr/sbin/augenrules: No change
```
I will check later on other OSs. This may need amending to capture different OS family types?

Can you confirm the OS you are running on?

Thanks again
uk-bolly

**Comment by mj84** [comment]
Hi @uk-bolly ,
now this is a funny one, I'm running Rocky Linux 9 as well:

```
[root@rocky9~]# cat /etc/redhat-release
Rocky Linux release 9.1 (Blue Onyx)
```

When I execute the command manually, I get this:

```
[root@rocky9 ~]# augenrules --check
/sbin/augenrules: No change
```

DNF however is telling me, augenrules has been installed to /usr/sbin/augenrules:

```
[root@rocky9 ~]# dnf provides /sbin/augenrules
Last metadata expiration check: 2:39:07 ago on Fri 10 Mar 2023 02:29:35 PM CET.
audit-3.0.7-103.el9.x86_64 : User space tools for kernel auditing
Repo        : @System
Matched from:
Filename    : /usr/sbin/augenrules

audit-3.0.7-103.el9.x86_64 : User space tools for kernel auditing
Repo        : baseos
Matched from:
Filename    : /usr/sbin/augenrules
```

On my installation there is a symlink from /sbin to /usr/sbin (which I didn't create) and /sbin/augenrules takes precedence, because of my $PATH variable:

```
[root@rocky9 ~]# echo $PATH
/root/.local/bin:/root/bin:/sbin:/bin:/usr/sbin:/usr/bin
```

However when I call augenrules by its full path, I receive the correct output:

```
[root@rocky9 ~]# /usr/sbin/augenrules --check
/usr/sbin/augenrules: No change
```
So I'm starting to think that the command should be changed rather than its expected output..

Best regards,
Markus

**Comment by uk-bolly** [comment]
hi @mj84 

I feel you are correct, i was thinking wonder it was a path issue :). Thanks for proving the point.
If you wanted to change the PR to change the command i am happy to approve.

Thanks again

uk-bolly

**Comment by mj84** [comment]
Hi @uk-bolly 

there you go :)

Cheers
Markus

**Review by uk-bolly — APPROVED** [review]
perfect

**Comment by uk-bolly** [comment]
Thank you thats merged :)

**Pull request merged**
